### ISSUE TITLE
Receive payment via Lightning Address

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash#14] opened 2023-10-30 22:12 UTC
This task is to replace the galoy lightning address with the IBEX lightning address and update the address domain name to be flashapp.me, but forward to an IBEX LNURL.

This should be done using accounts USD wallet

This task involves the following at minimum:

- [x] Call Ibex to create new static lnurl-pay during wallet creation and save to mongo in the `wallets` collection
- [x] Update GraphQL schema to expose `lnurlp` field for both PublicWallet and MeQuery
- [x] Update .well-known endpoint to fetch lnurlp from flash server  
- [x] Set Lightning Address Domain in `flash` server to point to `flash-pay` containing /.well-known/lnurlp endpoint

 The QR code showing on the Paycode screen should display an LNURL that is associated to the users IBEX account

**Comment by brh28** [comment] 2024-01-25 14:09
Slack thread with Ibex team for reference: https://app.slack.com/client/T04CSQZHNPK/C04K5NC9D3N

**Comment by brh28** [comment] 2024-02-02 17:48
Testing lightning address:

- External wallets are not able to reach .well-known endpoint due to ssl error in staging
- When calling .well-known endpoint within staging server (i.e bypass ssl), getting server error:
```
accountUsername = ben
error getting lnurl for user: ApolloError: fetch failed
    at new ApolloError (/app/node_modules/@apollo/client/errors/errors.cjs:31:28)
    at /app/node_modules/@apollo/client/core/core.cjs:1863:19
    at both (/app/node_modules/@apollo/client/utilities/utilities.cjs:1072:53)
    at /app/node_modules/@apollo/client/utilities/utilities.cjs:1065:72
    at new Promise (<anonymous>)
    at Object.then (/app/node_modules/@apollo/client/utilities/utilities.cjs:1065:24)
    at Object.error (/app/node_modules/@apollo/client/utilities/utilities.cjs:1073:49)
    at notifySubscription (/app/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/app/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/app/node_modules/zen-observable/lib/Observable.js:240:7) {
  graphQLErrors: [],
  protocolErrors: [],
  clientErrors: [],
  networkError: TypeError: fetch failed
      at node:internal/deps/undici/undici:12344:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    cause: Error: getaddrinfo ENOTFOUND undefined
        at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
      errno: -3008,
      code: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: 'undefined'
    }
  },
  extraInfo: undefined
}
```

**Comment by islandbitcoin** [comment] 2024-02-02 19:10
I was able to show the QR code after messing with the HSTS settings on Chrome, definitely needs some fixing:
<img width="250" alt="Screenshot 2024-02-02 at 2 10 07 PM" src="https://github.com/lnflash/flash/assets/34528298/7592b63a-b55e-4f30-9727-63c18f40e137">

**Comment by brh28** [comment] 2024-03-19 00:26
Integration testing failing due to incorrect response. We're returning:

```
{
"callback":"https://api-sandbox.poweredbyibex.io/lnurl/pay/invoice?k1=65d31dc0729a26c192db51562f0fdf4d51f9a20e0e541188639e53214081d945",
"fixed":false,
"min":1,
"max":100000000,
"domain":"api-sandbox.poweredbyibex.io",
"metadata":[["text/plain","Paying to LnUrl Pay"]],
"identifier":"ben@pay.staging.flashapp.me",
"description":"Paying to LnUrl Pay",
"image":"",
"commentAllowed":140
}
```
Meanwhile, [Luds](https://github.com/lnurl/luds/blob/luds/06.md) provide sample response:
```
{
    "callback": string, // The URL from LN SERVICE which will accept the pay request parameters
    "maxSendable": number, // Max millisatoshi amount LN SERVICE is willing to receive
    "minSendable": number, // Min millisatoshi amount LN SERVICE is willing to receive, can not be less than 1 or more than `maxSendable`
    "metadata": string, // Metadata json which must be presented as raw string here, this is required to pass signature verification at a later step
    "tag": "payRequest" // Type of LNURL
}
```
Our response is modeled after Galoy which uses the [lnurl-pay](https://www.npmjs.com/package/lnurl-pay) library. 

Not sure if it's the cause, but `lnurl-pay` lib is a few major versions behind and Galoy downstream has since made changes to their codebase at this endpoint

**Comment by brh28** [comment] 2024-03-19 00:27
Closing as this belongs here: https://github.com/lnflash/flash/issues/14

**Comment by brh28** [comment] 2024-03-26 14:11
Sucessfully tested Lightning address at `pay.staging.flashapp.me`. Only part remaining is changing the host

**Closed** 2024-03-27 23:02 UTC
Labels: Important
